org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=256m
android.useAndroidX=true
systemProp.http.socketTimeout=600000
systemProp.http.connectionTimeout=600000
systemProp.java.net.preferIPv4Stack=true
systemProp.sun.net.client.defaultConnectTimeout=600000
systemProp.sun.net.client.defaultReadTimeout=600000
