org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=256m
android.useAndroidX=true
systemProp.http.socketTimeout=120000
systemProp.http.connectionTimeout=120000
systemProp.java.net.preferIPv4Stack=true
systemProp.sun.net.client.defaultConnectTimeout=120000
systemProp.sun.net.client.defaultReadTimeout=120000
