import 'package:flutter/material.dart';

import 'models.dart';

const mockCategories = <MarketplaceCategory>[
  MarketplaceCategory(
    id: 'books',
    name: 'Libros',
    emoji: '\u{1F4DA}',
    icon: Icons.menu_book_rounded,
    color: Color(0xFF2A6FBB),
  ),
  MarketplaceCategory(
    id: 'notes',
    name: 'Apuntes',
    emoji: '\u{1F4DD}',
    icon: Icons.article_rounded,
    color: Color(0xFFD97706),
  ),
  MarketplaceCategory(
    id: 'electronics',
    name: 'Electrónicos',
    emoji: '\u{1F4BB}',
    icon: Icons.devices_rounded,
    color: Color(0xFF1B998B),
  ),
  MarketplaceCategory(
    id: 'clothes',
    name: 'Ropa',
    emoji: '\u{1F454}',
    icon: Icons.checkroom_rounded,
    color: Color(0xFF9B5DE5),
  ),
  MarketplaceCategory(
    id: 'services',
    name: 'Servicios',
    emoji: '\u{1F6E0}\uFE0F',
    icon: Icons.construction_rounded,
    color: Color(0xFFE76F51),
  ),
  MarketplaceCategory(
    id: 'food',
    name: 'Comida',
    emoji: '\u{1F355}',
    icon: Icons.restaurant_rounded,
    color: Color(0xFFE86F2C),
  ),
  MarketplaceCategory(
    id: 'housing',
    name: 'Hospedaje',
    emoji: '\u{1F6CF}\uFE0F',
    icon: Icons.bed_rounded,
    color: Color(0xFF6A994E),
  ),
  MarketplaceCategory(
    id: 'other',
    name: 'Otros',
    emoji: '\u{1F4E6}',
    icon: Icons.category_rounded,
    color: Color(0xFF607D8B),
  ),
];

const mockSellers = <Seller>[
  Seller(
    name: 'Ana Martinez',
    avatarInitials: 'AM',
    major: 'Medicina, 5to semestre',
    rating: 4.9,
    reviews: 28,
    verified: true,
  ),
  Seller(
    name: 'Carlos Vega',
    avatarInitials: 'CV',
    major: 'Ingenieria, 7mo semestre',
    rating: 4.7,
    reviews: 15,
    verified: true,
  ),
  Seller(
    name: 'Lucia Torres',
    avatarInitials: 'LT',
    major: 'Contaduria, 3er semestre',
    rating: 4.8,
    reviews: 19,
    verified: false,
  ),
  Seller(
    name: 'Mateo Ruiz',
    avatarInitials: 'MR',
    major: 'Arquitectura, 6to semestre',
    rating: 4.6,
    reviews: 11,
    verified: true,
  ),
  Seller(
    name: 'Sofia Hernandez',
    avatarInitials: 'SH',
    major: 'Nutricion, 4to semestre',
    rating: 5.0,
    reviews: 34,
    verified: true,
  ),
  Seller(
    name: 'Diego Salinas',
    avatarInitials: 'DS',
    major: 'Sistemas, 8vo semestre',
    rating: 4.5,
    reviews: 9,
    verified: true,
  ),
  Seller(
    name: 'Mariana Lopez',
    avatarInitials: 'ML',
    major: 'Psicologia, 2do semestre',
    rating: 4.8,
    reviews: 22,
    verified: true,
  ),
  Seller(
    name: 'Emilio Navarro',
    avatarInitials: 'EN',
    major: 'Administracion, 6to semestre',
    rating: 4.4,
    reviews: 7,
    verified: false,
  ),
  Seller(
    name: 'Valeria Cruz',
    avatarInitials: 'VC',
    major: 'Musica, 5to semestre',
    rating: 4.9,
    reviews: 17,
    verified: true,
  ),
];

final mockProducts = <Product>[
  Product(
    id: 'p1',
    title: 'MacBook Air M1 2020 en buen estado',
    price: 9800.0,
    category: mockCategories[2],
    description:
        'Laptop ligera para clases, tareas y edicion basica. Tiene 8 GB de RAM, 256 GB SSD, cargador original y bateria en buen estado. Entrego en biblioteca o cafeteria central.',
    publishedAgo: 'Hace 12 min',
    seller: mockSellers[1],
    imageIcon: Icons.laptop_mac_rounded,
    imageColor: const Color(0xFF2A6FBB),
    isFeatured: true,
    isFavorite: true,
  ),
  Product(
    id: 'p2',
    title: 'Pack de libros de Anatomia + apuntes',
    price: 850.0,
    category: mockCategories[0],
    description:
        'Incluye atlas, cuaderno de laboratorio y apuntes resumidos por unidades. Ideal para primer y segundo semestre. Sin hojas faltantes.',
    publishedAgo: 'Hace 30 min',
    seller: mockSellers[0],
    imageIcon: Icons.menu_book_rounded,
    imageColor: const Color(0xFFD97706),
    isFeatured: true,
  ),
  Product(
    id: 'p3',
    title: 'Tutoria de Calculo I antes de examenes',
    price: 120.0,
    category: mockCategories[4],
    description:
        'Sesiones de repaso con ejercicios tipo examen, limites, derivadas y aplicaciones. Puedo atender en biblioteca o por videollamada.',
    publishedAgo: 'Hace 1 h',
    seller: mockSellers[3],
    imageIcon: Icons.functions_rounded,
    imageColor: const Color(0xFFE76F51),
    isFeatured: true,
  ),
  Product(
    id: 'p4',
    title: 'Mini refri para dormitorio',
    price: 1750.0,
    category: mockCategories[7],
    description:
        'Frigobar compacto, enfria bien y cabe debajo de escritorio. Tiene pequenas marcas de uso pero funciona sin problema.',
    publishedAgo: 'Hace 2 h',
    seller: mockSellers[2],
    imageIcon: Icons.kitchen_rounded,
    imageColor: const Color(0xFF6A994E),
    isFeatured: true,
  ),
  Product(
    id: 'p5',
    title: 'iPad 9na gen con Apple Pencil generico',
    price: 5200.0,
    previousPrice: 5900.0,
    discountLabel: '-12%',
    isOffer: true,
    category: mockCategories[2],
    description:
        'Perfecto para tomar apuntes. Incluye funda, mica instalada y lapiz compatible. Entrego con caja y cargador.',
    publishedAgo: 'Hace 3 h',
    seller: mockSellers[5],
    imageIcon: Icons.tablet_mac_rounded,
    imageColor: const Color(0xFF1B998B),
    isFeatured: true,
  ),
  Product(
    id: 'p6',
    title: 'Paquete semanal de comida saludable',
    price: 390.0,
    previousPrice: 450.0,
    discountLabel: '-13%',
    isOffer: true,
    category: mockCategories[5],
    description:
        'Meal prep con 5 comidas balanceadas. Menu cambia cada semana. Entrego en residencias o cafeteria.',
    publishedAgo: 'Hace 4 h',
    seller: mockSellers[4],
    imageIcon: Icons.restaurant_rounded,
    imageColor: const Color(0xFFE76F51),
    isFeatured: true,
  ),
  Product(
    id: 'p7',
    title: 'Guitarra acustica Yamaha F310',
    price: 2400.0,
    category: mockCategories[7],
    description:
        'Guitarra con cuerdas nuevas, afinador y funda suave. Ideal para clases, ensayos o ministerio de musica.',
    publishedAgo: 'Hace 5 h',
    seller: mockSellers[8],
    imageIcon: Icons.music_note_rounded,
    imageColor: const Color(0xFF607D8B),
    isFeatured: true,
  ),
  Product(
    id: 'p8',
    title: 'Sudadera UM talla M color azul',
    price: 280.0,
    previousPrice: 350.0,
    discountLabel: '-20%',
    isOffer: true,
    category: mockCategories[3],
    description:
        'Sudadera universitaria con poco uso. Talla M, corte regular. La vendo porque me quedo chica.',
    publishedAgo: 'Hace 6 h',
    seller: mockSellers[0],
    imageIcon: Icons.checkroom_rounded,
    imageColor: const Color(0xFF9B5DE5),
  ),
  Product(
    id: 'p9',
    title: 'Apuntes de Bioquimica ordenados por tema',
    price: 90.0,
    category: mockCategories[1],
    description:
        'Resumen digital impreso con mapas, tablas y preguntas frecuentes de clase. Entrego engargolado.',
    publishedAgo: 'Hoy, 8:40 AM',
    seller: mockSellers[2],
    imageIcon: Icons.article_rounded,
    imageColor: const Color(0xFF0B4F8A),
  ),
  Product(
    id: 'p10',
    title: 'Audifonos Sony WH-CH520',
    price: 750.0,
    previousPrice: 920.0,
    discountLabel: '-18%',
    isOffer: true,
    category: mockCategories[2],
    description:
        'Audifonos Bluetooth con caja y cable. Funcionan perfecto para estudiar o tomar clases en linea.',
    publishedAgo: 'Hoy, 7:15 AM',
    seller: mockSellers[1],
    imageIcon: Icons.headphones_rounded,
    imageColor: const Color(0xFF1B998B),
  ),
  Product(
    id: 'p11',
    title: 'Calculadora Casio fx-991EX',
    price: 430.0,
    previousPrice: 520.0,
    discountLabel: '-17%',
    isOffer: true,
    category: mockCategories[2],
    description:
        'Calculadora cientifica permitida para la mayoria de clases. Tiene tapa y funciona con pila solar.',
    publishedAgo: 'Ayer',
    seller: mockSellers[3],
    imageIcon: Icons.calculate_rounded,
    imageColor: const Color(0xFF607D8B),
    isFavorite: true,
  ),
  Product(
    id: 'p12',
    title: 'Silla de escritorio ergonomica',
    price: 620.0,
    category: mockCategories[7],
    description:
        'Silla comoda para estudiar, con altura ajustable. El tapizado esta limpio y sin rasgaduras.',
    publishedAgo: 'Ayer',
    seller: mockSellers[2],
    imageIcon: Icons.chair_alt_rounded,
    imageColor: const Color(0xFF6A994E),
  ),
  Product(
    id: 'p13',
    title: 'Diseno de presentaciones para exposiciones',
    price: 150.0,
    category: mockCategories[4],
    description:
        'Armo presentaciones limpias con portada, graficas y estructura clara. Entrego editable en PowerPoint o Canva.',
    publishedAgo: 'Ayer',
    seller: mockSellers[0],
    imageIcon: Icons.slideshow_rounded,
    imageColor: const Color(0xFFE76F51),
  ),
  Product(
    id: 'p14',
    title: 'Uniforme clinico blanco talla S',
    price: 360.0,
    previousPrice: 480.0,
    discountLabel: '-25%',
    isOffer: true,
    category: mockCategories[3],
    description:
        'Filipina y pantalon blanco para practicas. Muy cuidado, sin manchas. Entrego lavado y planchado.',
    publishedAgo: 'Hace 2 dias',
    seller: mockSellers[6],
    imageIcon: Icons.local_hospital_rounded,
    imageColor: const Color(0xFF9B5DE5),
  ),
  Product(
    id: 'p15',
    title: 'Kit de dibujo tecnico con escuadras',
    price: 210.0,
    category: mockCategories[0],
    description:
        'Incluye escuadras, compas, escalimetro y portaminas. Lo use un semestre en dibujo arquitectonico.',
    publishedAgo: 'Hace 2 dias',
    seller: mockSellers[3],
    imageIcon: Icons.architecture_rounded,
    imageColor: const Color(0xFF2A6FBB),
  ),
  Product(
    id: 'p16',
    title: 'Monitor Samsung 24 pulgadas Full HD',
    price: 1900.0,
    previousPrice: 2300.0,
    discountLabel: '-17%',
    isOffer: true,
    category: mockCategories[2],
    description:
        'Monitor sin pixeles muertos, entrada HDMI y base original. Excelente para programar o editar trabajos.',
    publishedAgo: 'Hace 2 dias',
    seller: mockSellers[5],
    imageIcon: Icons.desktop_windows_rounded,
    imageColor: const Color(0xFF1B998B),
  ),
  Product(
    id: 'p17',
    title: 'Mesa plegable para cuarto',
    price: 320.0,
    category: mockCategories[7],
    description:
        'Mesa compacta para estudiar o comer. Se dobla facil y cabe bajo la cama.',
    publishedAgo: 'Hace 3 dias',
    seller: mockSellers[7],
    imageIcon: Icons.table_restaurant_rounded,
    imageColor: const Color(0xFF6A994E),
  ),
  Product(
    id: 'p18',
    title: 'Servicio de impresion y engargolado',
    price: 1.5,
    category: mockCategories[4],
    description:
        'Impresiones en blanco y negro o color. Tambien hago engargolados para proyectos finales. Entrega en biblioteca.',
    publishedAgo: 'Hace 3 dias',
    seller: mockSellers[7],
    imageIcon: Icons.print_rounded,
    imageColor: const Color(0xFFE76F51),
  ),
  Product(
    id: 'p19',
    title: 'Mochila impermeable para laptop',
    price: 480.0,
    previousPrice: 620.0,
    discountLabel: '-23%',
    isOffer: true,
    category: mockCategories[3],
    description:
        'Mochila negra con compartimento acolchado para laptop de hasta 15 pulgadas. Tiene puerto USB lateral.',
    publishedAgo: 'Hace 4 dias',
    seller: mockSellers[6],
    imageIcon: Icons.backpack_rounded,
    imageColor: const Color(0xFF9B5DE5),
  ),
  Product(
    id: 'p20',
    title: 'Termo Stanley 887 ml color verde',
    price: 520.0,
    previousPrice: 690.0,
    discountLabel: '-25%',
    isOffer: true,
    category: mockCategories[7],
    description:
        'Termo original con pocas marcas de uso. Mantiene frio todo el dia, ideal para clases largas.',
    publishedAgo: 'Hace 4 dias',
    seller: mockSellers[4],
    imageIcon: Icons.local_drink_rounded,
    imageColor: const Color(0xFF607D8B),
  ),
  Product(
    id: 'p21',
    title: 'Libro de Psicologia del desarrollo',
    price: 300.0,
    category: mockCategories[0],
    description:
        'Edicion reciente con subrayado moderado. Incluye separadores por capitulo y resumen digital.',
    publishedAgo: 'Hace 5 dias',
    seller: mockSellers[6],
    imageIcon: Icons.psychology_rounded,
    imageColor: const Color(0xFF2A6FBB),
  ),
  Product(
    id: 'p22',
    title: 'Cafetera individual para dormitorio',
    price: 390.0,
    previousPrice: 500.0,
    discountLabel: '-22%',
    isOffer: true,
    category: mockCategories[7],
    description:
        'Cafetera pequena para una taza. Funciona bien y no ocupa mucho espacio en escritorio.',
    publishedAgo: 'Hace 5 dias',
    seller: mockSellers[8],
    imageIcon: Icons.coffee_maker_rounded,
    imageColor: const Color(0xFF6A994E),
  ),
  Product(
    id: 'p23',
    title: 'Clases de guitarra para principiantes',
    price: 100.0,
    category: mockCategories[4],
    description:
        'Acordes basicos, rasgueos, lectura sencilla y preparacion para participar en grupos de alabanza.',
    publishedAgo: 'Hace 6 dias',
    seller: mockSellers[8],
    imageIcon: Icons.library_music_rounded,
    imageColor: const Color(0xFFE76F51),
  ),
  Product(
    id: 'p24',
    title: 'Router WiFi TP-Link doble banda',
    price: 650.0,
    category: mockCategories[2],
    description:
        'Router en perfecto estado, ideal para departamento compartido. Incluye adaptador y cable Ethernet.',
    publishedAgo: 'Hace 6 dias',
    seller: mockSellers[5],
    imageIcon: Icons.router_rounded,
    imageColor: const Color(0xFF1B998B),
  ),
  // ─── SanksUm (Comida) ────────────────────────────────────────
  Product(
    id: 'f1',
    title: 'Chilaquiles del dia con pollo',
    price: 55.0,
    category: mockCategories[5],
    description:
        'Chilaquiles verdes o rojos con pollo, crema y queso. Servidos de 8:00 AM a 11:00 AM en la cafeteria central. Incluye bebida pequena.',
    publishedAgo: 'Hoy 8:00 AM',
    seller: mockFoodEstablishment,
    imageIcon: Icons.ramen_dining_rounded,
    imageColor: const Color(0xFFD32F2F),
    isFeatured: true,
  ),
  Product(
    id: 'f2',
    title: 'Quesadilla de harina con ingredientes',
    price: 30.0,
    category: mockCategories[5],
    description:
        'Quesadilla de harina preparada al momento con queso Oaxaca. Puedes agregar pollo, tinga o champiñones por \$10 extra.',
    publishedAgo: 'Hoy 9:15 AM',
    seller: mockFoodEstablishment,
    imageIcon: Icons.lunch_dining_rounded,
    imageColor: const Color(0xFFE65100),
  ),
  Product(
    id: 'f3',
    title: 'Burrito de pollo o carne',
    price: 45.0,
    previousPrice: 52.0,
    discountLabel: '-13%',
    isOffer: true,
    category: mockCategories[5],
    description:
        'Burrito grande con arroz, frijoles, pollo o carne asada, crema y guacamole. Promocion especial de mitad de semana.',
    publishedAgo: 'Hoy 10:30 AM',
    seller: mockFoodEstablishment,
    imageIcon: Icons.takeout_dining_rounded,
    imageColor: const Color(0xFFBF360C),
    isFeatured: true,
  ),
  Product(
    id: 'f4',
    title: 'Agua fresca de horchata 500ml',
    price: 18.0,
    category: mockCategories[5],
    description:
        'Agua fresca de horchata natural, preparada diariamente. Tambien tenemos jamaica y limon.',
    publishedAgo: 'Hoy 11:00 AM',
    seller: mockFoodEstablishment,
    imageIcon: Icons.local_drink_rounded,
    imageColor: const Color(0xFFF9A825),
  ),
  Product(
    id: 'f5',
    title: 'Torta de jamon con verduras',
    price: 38.0,
    category: mockCategories[5],
    description:
        'Torta en telera crujiente con jamon, queso, aguacate, lechuga y tomate. Preparada al momento.',
    publishedAgo: 'Hoy 12:15 PM',
    seller: mockFoodEstablishment,
    imageIcon: Icons.fastfood_rounded,
    imageColor: const Color(0xFF795548),
  ),
  Product(
    id: 'f6',
    title: 'Papas fritas con salsa y queso',
    price: 25.0,
    previousPrice: 32.0,
    discountLabel: '-22%',
    isOffer: true,
    category: mockCategories[5],
    description:
        'Orden de papas fritas bañadas en salsa de queso amarillo y chipotle. Ideal para compartir entre clases.',
    publishedAgo: 'Hoy 1:00 PM',
    seller: mockFoodEstablishment,
    imageIcon: Icons.dinner_dining_rounded,
    imageColor: const Color(0xFFF57F17),
  ),
  Product(
    id: 'f7',
    title: 'Hot dog completo',
    price: 28.0,
    category: mockCategories[5],
    description:
        'Hot dog con salchicha, pan suave, salsa de tomate, mostaza, mayonesa, cebolla y jalapenos.',
    publishedAgo: 'Hoy 2:30 PM',
    seller: mockFoodEstablishment,
    imageIcon: Icons.dining_rounded,
    imageColor: const Color(0xFFD84315),
  ),
  Product(
    id: 'f8',
    title: 'Combo estudiante: torta + agua',
    price: 50.0,
    previousPrice: 56.0,
    discountLabel: '-11%',
    isOffer: true,
    category: mockCategories[5],
    description:
        'Combo torta de tu preferencia + agua fresca 500ml. Ahorra \$6 con este combo exclusivo.',
    publishedAgo: 'Promo permanente',
    seller: mockFoodEstablishment,
    imageIcon: Icons.set_meal_rounded,
    imageColor: const Color(0xFFE65100),
    isFeatured: true,
    isFavorite: true,
  ),
  // ─── Hospedaje ───────────────────────────────────────────────
  Product(
    id: 'h1',
    title: 'Cuarto amueblado cerca de biblioteca',
    price: 2800.0,
    category: mockCategories[6],
    description:
        'Cuarto individual con cama, escritorio y closet. Bano compartido con 2 personas. Agua y luz incluidos.',
    publishedAgo: 'Disponible desde agosto',
    seller: mockSellers[1],
    imageIcon: Icons.bedroom_parent_rounded,
    imageColor: const Color(0xFF4E342E),
    isFeatured: true,
  ),
  Product(
    id: 'h2',
    title: 'Departamento compartido 2 habs',
    price: 3500.0,
    category: mockCategories[6],
    description:
        'Departamento con sala, cocina equipada, 2 habitaciones y bano. Internet incluido.',
    publishedAgo: 'Disponible inmediato',
    seller: mockSellers[5],
    imageIcon: Icons.apartment_rounded,
    imageColor: const Color(0xFF3E2723),
  ),
  Product(
    id: 'h3',
    title: 'Residencia femenil cerca de la uni',
    price: 2500.0,
    category: mockCategories[6],
    description:
        'Residencia exclusiva para mujeres. Cuarto individual con closet, areas comunes, cocina y lavanderia.',
    publishedAgo: 'Disponible desde septiembre',
    seller: mockHousingHost,
    imageIcon: Icons.home_work_rounded,
    imageColor: const Color(0xFF6D4C41),
    isFeatured: true,
  ),
  Product(
    id: 'h4',
    title: 'Sofa cama en sala de departamento',
    price: 1800.0,
    previousPrice: 2100.0,
    discountLabel: '-14%',
    isOffer: true,
    category: mockCategories[6],
    description:
        'Sofa cama individual en sala de departamento amplio. Compartes con 2 roomies tranquilos. Servicios incluidos.',
    publishedAgo: 'Disponible inmediato',
    seller: mockSellers[3],
    imageIcon: Icons.weekend_rounded,
    imageColor: const Color(0xFF5D4037),
  ),
];

// ─── Establecimientos ──────────────────────────────────────────────

const mockFoodEstablishment = Seller(
  name: 'SanksUm',
  avatarInitials: 'SU',
  major: 'Cafeteria UM • Establecimiento',
  rating: 4.7,
  reviews: 56,
  verified: true,
);

const mockHousingHost = Seller(
  name: 'Residencias UM',
  avatarInitials: 'RU',
  major: 'Hospedaje universitario',
  rating: 4.5,
  reviews: 23,
  verified: true,
);

// ─── Productos de SanksUm (Comida) ─────────────────────────────────

final mockFoodProducts = <Product>[
  Product(
    id: 'f1',
    title: 'Chilaquiles del dia con pollo',
    price: 55.0,
    category: mockCategories[5],
    description:
        'Chilaquiles verdes o rojos con pollo, crema y queso. Servidos de 8:00 AM a 11:00 AM en la cafeteria central. Incluye bebida pequena.',
    publishedAgo: 'Disponible hoy',
    seller: mockFoodEstablishment,
    imageIcon: Icons.ramen_dining_rounded,
    imageColor: Color(0xFFD32F2F),
    isFeatured: true,
    isOffer: false,
  ),
  Product(
    id: 'f2',
    title: 'Quesadilla de harina con ingredientes',
    price: 30.0,
    category: mockCategories[5],
    description:
        'Quesadilla de harina preparada al momento con queso Oaxaca. Puedes agregar pollo, tinga o champiñones por \$10 extra.',
    publishedAgo: 'Disponible hoy',
    seller: mockFoodEstablishment,
    imageIcon: Icons.lunch_dining_rounded,
    imageColor: Color(0xFFE65100),
  ),
  Product(
    id: 'f3',
    title: 'Burrito de pollo o carne',
    price: 45.0,
    previousPrice: 52.0,
    discountLabel: '-13%',
    isOffer: true,
    category: mockCategories[5],
    description:
        'Burrito grande con arroz, frijoles, pollo o carne asada, crema y guacamole. Promocion especial de mitad de semana.',
    publishedAgo: 'Oferta del dia',
    seller: mockFoodEstablishment,
    imageIcon: Icons.takeout_dining_rounded,
    imageColor: Color(0xFFBF360C),
    isFeatured: true,
  ),
  Product(
    id: 'f4',
    title: 'Agua fresca de horchata 500ml',
    price: 18.0,
    category: mockCategories[5],
    description:
        'Agua fresca de horchata natural, preparada diariamente. Tambien tenemos jamaica y limon. Pregunta por el combo con comida.',
    publishedAgo: 'Disponible hoy',
    seller: mockFoodEstablishment,
    imageIcon: Icons.local_drink_rounded,
    imageColor: Color(0xFFF9A825),
  ),
  Product(
    id: 'f5',
    title: 'Torta de jamon con verduras',
    price: 38.0,
    category: mockCategories[5],
    description:
        'Torta en telera crujiente con jamon, queso, aguacate, lechuga y tomate. Preparada al momento en la cafeteria.',
    publishedAgo: 'Disponible hoy',
    seller: mockFoodEstablishment,
    imageIcon: Icons.fastfood_rounded,
    imageColor: Color(0xFF795548),
  ),
  Product(
    id: 'f6',
    title: 'Papas fritas con salsa y queso',
    price: 25.0,
    previousPrice: 32.0,
    discountLabel: '-22%',
    isOffer: true,
    category: mockCategories[5],
    description:
        'Orden de papas fritas bañadas en salsa de queso amarillo y chipotle. Ideal para compartir entre clases.',
    publishedAgo: 'Oferta del dia',
    seller: mockFoodEstablishment,
    imageIcon: Icons.dinner_dining_rounded,
    imageColor: Color(0xFFF57F17),
  ),
  Product(
    id: 'f7',
    title: 'Hot dog completo',
    price: 28.0,
    category: mockCategories[5],
    description:
        'Hot dog con salchicha, pan suave, salsa de tomate, mostaza, mayonesa, cebolla y jalapenos. Tu eliges los ingredientes.',
    publishedAgo: 'Disponible hoy',
    seller: mockFoodEstablishment,
    imageIcon: Icons.dining_rounded,
    imageColor: Color(0xFFD84315),
  ),
  Product(
    id: 'f8',
    title: 'Combo estudiante: torta + agua',
    price: 50.0,
    previousPrice: 56.0,
    discountLabel: '-11%',
    isOffer: true,
    category: mockCategories[5],
    description:
        'Combo que incluye torta de tu preferencia + agua fresca 500ml. Ahorra \$6 con este combo exclusivo para estudiantes.',
    publishedAgo: 'Promo permanente',
    seller: mockFoodEstablishment,
    imageIcon: Icons.set_meal_rounded,
    imageColor: Color(0xFFE65100),
    isFeatured: true,
    isFavorite: true,
  ),
];

// ─── Productos de Hospedaje ────────────────────────────────────────

final mockHousingProducts = <Product>[
  Product(
    id: 'h1',
    title: 'Cuarto amueblado cerca de biblioteca',
    price: 2800.0,
    category: mockCategories[6],
    description:
        'Cuarto individual con cama, escritorio y closet. Bano compartido con 2 personas. Agua y luz incluidos. A 3 min caminando de la biblioteca central.',
    publishedAgo: 'Disponible desde agosto',
    seller: mockSellers[1],
    imageIcon: Icons.bedroom_parent_rounded,
    imageColor: Color(0xFF4E342E),
    isFeatured: true,
  ),
  Product(
    id: 'h2',
    title: 'Departamento compartido 2 habitaciones',
    price: 3500.0,
    category: mockCategories[6],
    description:
        'Departamento con sala, cocina equipada, 2 habitaciones y bano. Rentamos una habitacion. Ideal para estudiante responsable. Internet incluido.',
    publishedAgo: 'Disponible inmediato',
    seller: mockSellers[5],
    imageIcon: Icons.apartment_rounded,
    imageColor: Color(0xFF3E2723),
  ),
  Product(
    id: 'h3',
    title: 'Residencia femenil cerca de la uni',
    price: 2500.0,
    category: mockCategories[6],
    description:
        'Residencia exclusiva para mujeres. Cuarto individual con closet, areas comunes, cocina y lavanderia. Reglas claras y ambiente de estudio.',
    publishedAgo: 'Disponible desde septiembre',
    seller: mockHousingHost,
    imageIcon: Icons.home_work_rounded,
    imageColor: Color(0xFF6D4C41),
    isFeatured: true,
  ),
  Product(
    id: 'h4',
    title: 'Sofa cama en sala de departamento',
    price: 1800.0,
    category: mockCategories[6],
    description:
        'Sofa cama individual en sala de departamento amplio. Compartes con 2 roomies tranquilos. Ideal para presupuesto ajustado. Servicios incluidos.',
    publishedAgo: 'Disponible inmediato',
    seller: mockSellers[3],
    imageIcon: Icons.weekend_rounded,
    imageColor: Color(0xFF5D4037),
    isOffer: true,
    previousPrice: 2100.0,
    discountLabel: '-14%',
  ),
];

final mockOwnListings = <Product>[
  Product(
    id: 'o1',
    title: 'Bicicleta urbana rodada 26',
    price: 1200.0,
    category: mockCategories[7],
    description:
        'Bicicleta para moverse dentro del campus. Requiere ajuste menor de frenos.',
    publishedAgo: 'Activa desde ayer',
    seller: mockSellers[0],
    imageIcon: Icons.pedal_bike_rounded,
    imageColor: const Color(0xFF607D8B),
    status: ListingStatus.active,
  ),
  Product(
    id: 'o2',
    title: 'Libro de Ingles academico',
    price: 220.0,
    category: mockCategories[0],
    description: 'Libro usado durante un semestre, con pocas marcas en lapiz.',
    publishedAgo: 'Destaca 4 dias mas',
    seller: mockSellers[0],
    imageIcon: Icons.auto_stories_rounded,
    imageColor: const Color(0xFFD97706),
    isFeatured: true,
    status: ListingStatus.featured,
  ),
  Product(
    id: 'o3',
    title: 'Lampara de escritorio LED',
    price: 160.0,
    category: mockCategories[7],
    description: 'Lampara blanca con tres niveles de intensidad.',
    publishedAgo: 'Expirada hace 2 dias',
    seller: mockSellers[0],
    imageIcon: Icons.light_rounded,
    imageColor: const Color(0xFF6A994E),
    status: ListingStatus.expired,
  ),
  Product(
    id: 'o4',
    title: 'Tenis deportivos Nike talla 27',
    price: 690.0,
    category: mockCategories[3],
    description:
        'Tenis con poco uso para correr en pista o gimnasio. Suela en buen estado.',
    publishedAgo: 'Activa desde hace 3 dias',
    seller: mockSellers[0],
    imageIcon: Icons.directions_run_rounded,
    imageColor: const Color(0xFF9B5DE5),
    status: ListingStatus.active,
  ),
  Product(
    id: 'o5',
    title: 'Paquete de notas de Fisiologia',
    price: 140.0,
    category: mockCategories[1],
    description:
        'Notas impresas por sistemas, con esquemas y preguntas de repaso para examenes parciales.',
    publishedAgo: 'Destaca 1 dia mas',
    seller: mockSellers[0],
    imageIcon: Icons.fact_check_rounded,
    imageColor: const Color(0xFFD97706),
    isFeatured: true,
    status: ListingStatus.featured,
  ),
  Product(
    id: 'o6',
    title: 'Organizador plastico de cajones',
    price: 110.0,
    category: mockCategories[7],
    description:
        'Organizador para escritorio o closet. Limpio, sin piezas quebradas.',
    publishedAgo: 'Expirada hace 1 semana',
    seller: mockSellers[0],
    imageIcon: Icons.inventory_2_rounded,
    imageColor: const Color(0xFF6A994E),
    status: ListingStatus.expired,
  ),
];

final mockCartItems = <CartItem>[
  CartItem(
    id: 'c1',
    product: mockProducts[10],
    quantity: 1,
    meetingPoint: 'Biblioteca central, 4:00 PM',
  ),
  CartItem(
    id: 'c2',
    product: mockProducts[7],
    quantity: 1,
    meetingPoint: 'Residencias norte, 7:30 PM',
  ),
  CartItem(
    id: 'c3',
    product: mockProducts[19],
    quantity: 2,
    meetingPoint: 'Cafeteria UM, despues de capilla',
  ),
];

const highlightPlans = <HighlightPlan>[
  HighlightPlan(
    id: 'd1',
    title: 'Destacado 24h',
    price: r'$20',
    description: 'Para ventas rapidas y urgentes. Aparece arriba por un dia.',
    days: 1,
  ),
  HighlightPlan(
    id: 'd3',
    title: 'Destacado 3 dias',
    price: r'$40',
    description: 'Buena opcion para rotar inventario sin pagar de mas.',
    days: 3,
  ),
  HighlightPlan(
    id: 'd7',
    title: 'Destacado 7 dias',
    price: r'$70',
    description: 'Mayor visibilidad durante toda la semana escolar.',
    days: 7,
  ),
  HighlightPlan(
    id: 'm1',
    title: 'Plan mensual',
    price: r'$180',
    description:
        'Pensado para negocios fijos: aparece arriba en su categoria todo el mes.',
    days: 30,
  ),
];
